---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  # You may wish to disable always updating cookbooks in CI or other testing environments.
  # For example:
  #   always_update_cookbooks: <%= !ENV['CI'] %>
  always_update_cookbooks: true

verifier:
  name: inspec

platforms:
  - name: opscode-ubuntu-18.04-chef-14
    driver:
      box: bento/ubuntu-18.04
    provisioner:
      product_name: chef
      product_version: latest

suites:
  - name: default
    run_list:
      - recipe[pathfinder-node::first_node]
    verifier:
      inspec_tests:
        - test/integration/default
    attributes:
      pathfinder-node:
        custom_hostname: 'node-01'
        underlay_subnet: '10.0.0.0/16'
        overlay_subnet: '250.0.0.0/8'
