---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  # You may wish to disable always updating cookbooks in CI or other testing environments.
  # For example:
  #   always_update_cookbooks: <%= !ENV['CI'] %>
  always_update_cookbooks: true

verifier:
  name: inspec

platforms:
  - name: opscode-ubuntu-16.04-chef-12
    driver:
      box: bento/ubuntu-16.04
    provisioner:
      product_name: chef
      product_version: 12.21
  - name: opscode-ubuntu-16.04-chef-14
    driver:
      box: bento/ubuntu-16.04
    provisioner:
      product_name: chef
      product_version: latest

suites:
  - name: default
    run_list:
      - recipe[pathfinder-node::default]
    verifier:
      inspec_tests:
        - test/integration/default
    attributes:
